yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='home_page'),
    path('group/', views.index, name='home_page'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace = 'posts'))
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        'Group',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200)
    description = models.TextField

    def __str__(self):
        return self.title

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group

def index(request):
    text = 'Последние обновления на сайте'
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
        'text': text
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    text = 'Записи сообщества'
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'posts': posts,
        'group': group,
        'text': text
    }
    return render(request, 'posts/group_post.html', context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
{% load static %}
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:home_page' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>

yatube/templates/posts/group_post.html
{% extends 'base.html' %}

{% block title %}
  {{ text }}
{% endblock %}

{% block content %}
<div class="container py-5">

<h1>{{ group }}</h1>
</div>
<!-- класс py-5 создает отступы сверху и снизу блока -->
{% for item in posts %}
<div class="container py-4">


  <article>
    <ul>
      <li>
        {{ item.author }}
      </li>
      <li>
        {{ item.pub_date }}
      </li>
    </ul>
    <p>
      {{ item.text }}
    </p>
  </article>
  <hr>

</div>
{% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  {{ text }}
{% endblock %}

{% block content %}
  {% for item in posts %}
<div class="container py-5">
  <article>
    <ul>
      <li> {{item.author}} </li>
      <li> {{item.pub_date}} </li>
    </ul>
    <p> {{item.text}} </p>

    {% if item.group %}
      <button type="button" class="btn btn-outline-info">
        <p>
          {{item.group}}
          <a href="{% url 'posts:group_posts' item.group.slug %}">все записи группы</a>
        </p>
      </button>
    {% endif %}
  </article>
  <hr>
</div>
{% endfor %}
{% endblock %}